language: c
cache: ccache
sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - ca-certificates
            - build-essential
            - gfortran
            - subversion
            - ccache
            - libreadline-dev
            - libx11-dev
            - libxt-dev
            - zlib1g-dev
            - libbz2-dev
            - liblzma-dev
            - libpcre3-dev
            - libcurl4-openssl-dev
    - os: osx

install: make R-devel

script: make -j2 R-devel/build
